name=(input('enter your name'))
roll_no=(input('enter your roll_no'))
age=int(input('enter your age'))
weight=float(input('enter your weight'))
print(name,'name')
print(roll_no,'roll_no')
print(age,'age')
print(weight,'weight')  
